spring:
  resources:
    static-locations: classpath:/static, classpath:/vue
  freemarker:
    enabled: false
    cache: false
    charset: UTF-8
    content-type: text/html
    request-context-attribute: rc
    template-loader-path: classpath:/templates/
    suffix: .ftl

server:
  port: 9090
  servlet:
    context-path: /sql-parser-web


